### ISSUE TITLE
KASP- shifting form

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/care_fe#5384]
https://care.coronasafe.in/shifting/bc8b9d9a-e28b-4e85-b66b-4de4dea1f686/update

Make "Is Karunya Arogya Suraksha Padhathi?" appear only in War-mode configuration. 

This applied for the KASP field in shifting status update form as well as shifting details page (https://care.coronasafe.in/shifting/d350a891-0688-416f-8a50-a1c01a679c34)

Part of #5393

**Comment by aparnacoronasafe** [comment]
@rithviknishad I am so sorry. But I had a change the issue a bit. Could you please make the changes?

**Comment by rithviknishad** [comment]
@aparnacoronasafe I've updated the PR to include the field only when wartime is set

**Comment by gigincg** [comment]
@aparnacoronasafe 
1. KASP will be disabled in our production deployments. @mathew-alex @rithviknishad Can you confirm that it is already this way
2. When KASP (Or any other form of State Support Programme) is enabled by a state, shouldn't it be applicable in Peacetime as well?

cc: @rithviknishad

**Comment by mathew-alex** [comment]
> @aparnacoronasafe
> 
> 1. KASP will be disabled in our production deployments. @mathew-alex @rithviknishad Can you confirm that it is already this way
> 2. When KASP (Or any other form of State Support Programme) is enabled by a state, shouldn't it be applicable in Peacetime as well?
> 
> cc: @rithviknishad

KASP is disabled in production deployments.

**Comment by aparnacoronasafe** [comment]
@gigincg I can still see KASP in staging. hence the confusion.

If it is disabled, let it stay the same way. No change required. Could you please do the same in staging @mathew-alex so that the confusion doesnt arise.

@gigincg In our current requirements, there is no reservation in the field for any scheme. KASP even though an existing scheme acted as a reservation during COVID where the state had mentioned that so many beds must be reserved for KASP. Such a reservation system may only be required during war-time

**Comment by rithviknishad** [comment]
I'll also update it such that, the field is hidden when kasp is not enabled, instead of being dependent on wartime config.

**Comment by rithviknishad** [comment]
So far (as per the latest develop), the field was not hidden based on any configurations.

**Comment by khavinshankar** [comment]
@rithviknishad any updates on this?

**Comment by nihal467** [comment]
@khavinshankar @rithviknishad had communicated me through slack yesterday @6 in the evening and informed the discussed changes were pushed, so I will be testing the PR now
